vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       annonces_image:
           uri_prefix: /img/ImgUser
           upload_destination: '%kernel.project_dir%/public/img/ImgUser'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
